import { describe, expect, it } from "vitest";

import { signWebhook, verifyWebhook, WebhookVerificationError } from "../src/index.js";

// Golden vector generated by the engine's Go implementation
// (internal/webhook.Sign) — proves cross-language compatibility.
const GO_SECRET = "whsec_crosslang_test";
const GO_TS = 1700000000;
const GO_BODY = `{"event":"execution.completed","execution_id":"exe_1","status":"SUCCEEDED","attempts":2}`;
const GO_SIGNATURE = "sha256=2ef91bb368013c9950082137fd1aefd7e3802c405c9c9cf82277883d08e5295b";

describe("signWebhook", () => {
  it("matches the Go implementation byte for byte", () => {
    expect(signWebhook(GO_SECRET, GO_TS, GO_BODY)).toBe(GO_SIGNATURE);
  });
});

describe("verifyWebhook", () => {
  const valid = {
    secret: GO_SECRET,
    body: GO_BODY,
    signature: GO_SIGNATURE,
    timestamp: GO_TS,
    now: GO_TS + 10,
  };

  it("accepts a Go-signed delivery and parses the event", () => {
    const event = verifyWebhook(valid);
    expect(event.event).toBe("execution.completed");
    expect(event.executionId).toBe("exe_1");
    expect(event.status).toBe("SUCCEEDED");
    expect(event.attempts).toBe(2);
  });

  it("accepts body as bytes", () => {
    const event = verifyWebhook({ ...valid, body: new TextEncoder().encode(GO_BODY) });
    expect(event.executionId).toBe("exe_1");
  });

  it("rejects a tampered body", () => {
    const tampered = GO_BODY.replace("SUCCEEDED", "FAILED   ");
    expect(() => verifyWebhook({ ...valid, body: tampered })).toThrow(WebhookVerificationError);
  });

  it("rejects the wrong secret", () => {
    expect(() => verifyWebhook({ ...valid, secret: "whsec_wrong" })).toThrow("signature mismatch");
  });

  it("rejects a stale timestamp (replay protection)", () => {
    expect(() => verifyWebhook({ ...valid, now: GO_TS + 301 })).toThrow(/tolerance/);
  });

  it("allows disabling tolerance for offline testing", () => {
    const event = verifyWebhook({ ...valid, now: GO_TS + 999999, toleranceSeconds: 0 });
    expect(event.executionId).toBe("exe_1");
  });

  it("rejects a garbage timestamp header", () => {
    expect(() => verifyWebhook({ ...valid, timestamp: "not-a-number" })).toThrow(
      "invalid timestamp",
    );
  });

  it("parses error events with llm hints", () => {
    const body = JSON.stringify({
      event: "execution.failed",
      execution_id: "exe_2",
      status: "FAILED",
      attempts: 1,
      error: { code: "TARGET_REJECTED", message: "400", llm_hint: "fix the payload" },
    });
    const ts = 1700000100;
    const event = verifyWebhook({
      secret: GO_SECRET,
      body,
      signature: signWebhook(GO_SECRET, ts, body),
      timestamp: ts,
      now: ts,
    });
    expect(event.error?.code).toBe("TARGET_REJECTED");
    expect(event.error?.llmHint).toBe("fix the payload");
  });
});
